class Voicevox
  attr_reader use_gpu: bool
  attr_reader threads: Integer
  attr_reader load_all_models: bool

  alias gpu? use_gpu

  def initialize: -> void

  def initialized?: -> bool

  def init: (
    ?use_gpu: :auto | bool,
    ?threads: Integer?,
    ?load_all_models: bool
  ) -> void

  def finalize: -> void

  def load_openjtalk_dict: (String path) -> void

  type speaker = Voicevox::CharacterInfo | Voicevox::StyleInfo | Integer

  def load_model: (speaker speaker) -> void
  def model_loaded?: (speaker speaker) -> bool

  def tts: (String text, speaker speaker) -> String
  def tts_from_kana: (String text, speaker speaker) -> String
  alias aquestalk_tts tts_from_kana

  attr_accessor self.initialized: bool

  alias self.initialized? self.initialized
end
