module Voicevox::Core
  extend ::FFI::Library
  Uintptr: Symbol

  VoicevoxAccelerationMode: Symbol
  type voicevox_acceleration_mode =
      :voicevox_acceleration_mode_auto
    | :voicevox_acceleration_mode_cpu
    | :voicevox_acceleration_mode_gpu

  VoicevoxResultCode: Symbol
  type voicevox_result_code =
      :voicevox_result_ok
    | :voicevox_result_not_loaded_openjtalk_dict_error
    | :voicevox_result_load_model_error
    | :voicevox_result_get_supported_devices_error
    | :voicevox_result_gpu_support_error
    | :voicevox_result_load_metas_error
    | :voicevox_result_invalid_style_id_error
    | :voicevox_result_invalid_model_id_error
    | :voicevox_result_inference_error
    | :voicevox_result_extract_full_context_label_error
    | :voicevox_result_invalid_utf8_input_error
    | :voicevox_result_parse_kana_error
    | :voicevox_result_invalid_audio_query_error
    | :voicevox_result_invalid_accent_phrase_error
    | :voicevox_result_open_file_error
    | :voicevox_result_vvm_model_read_error
    | :voicevox_result_already_loaded_model_error
    | :voicevox_result_unloaded_model_error
    | :voicevox_result_load_user_dict_error
    | :voicevox_result_save_user_dict_error
    | :voicevox_result_unknown_user_dict_word_error
    | :voicevox_result_use_user_dict_error
    | :voicevox_result_invalid_user_dict_word_error
    | :voicevox_result_invalid_uuid_error

  VoicevoxUserDictWordType: Symbol
  type voicevox_user_dict_word_type =
      :voicevox_user_dict_word_type_proper_noun
    | :voicevox_user_dict_word_type_common_noun
    | :voicevox_user_dict_word_type_verb
    | :voicevox_user_dict_word_type_adjective
    | :voicevox_user_dict_word_type_suffix

  VoicevoxOpenJtalkRc: Symbol
  type voicevox_open_jtalk_rc = FFI::Pointer

  VoicevoxSynthesizer: Symbol
  type voicevox_synthesizer = FFI::Pointer

  VoicevoxUserDict: Symbol
  type voicevox_user_dict = FFI::Pointer

  VoicevoxVoiceModel: Symbol
  type voicevox_voice_model = FFI::Pointer

  VoicevoxVoiceModelId: Symbol
  type voicevox_voice_model_id = Integer

  class VoicevoxInitializeOptions
    attr_accessor acceleration_mode: voicevox_acceleration_mode
    attr_accessor cpu_num_threads: Integer
  end

  VoicevoxStyleId: Symbol

  class VoicevoxAudioQueryOptions < FFI::Struct
    attr_accessor kana: bool
  end

  class VoicevoxAccentPhraseOptions < FFI::Struct
    attr_accessor kana: bool
  end

  class VoicevoxSynthesisOptions < FFI::Struct
    attr_accessor enable_interrogative_upspeak: bool
  end

  class VoicevoxTtsOptions < FFI::Struct
    attr_accessor kana: bool
    attr_accessor enable_interrogative_upspeak: bool
  end

  class VoicevoxUserDictWord < FFI::Struct
    attr_accessor surface: String
    attr_accessor pronunciation: String
    attr_accessor accent_type: Integer
    attr_accessor word_type: voicevox_user_dict_word_type
    attr_accessor priority: Integer
  end

  def voicevox_make_default_initialize_options: -> VoicevoxInitializeOptions

  def voicevox_get_version: -> String

  def voicevox_make_default_audio_query_options: -> VoicevoxAudioQueryOptions

  def voicevox_make_default_accent_phrase_options: -> VoicevoxAccentPhraseOptions

  def voicevox_make_default_synthesis_options: -> VoicevoxSynthesisOptions

  def voicevox_make_default_tts_options: -> VoicevoxTtsOptions

  def voicevox_open_jtalk_rc_new: (String open_jtalk_dic_dir, voicevox_open_jtalk_rc open_jtalk) -> voicevox_result_code

  def voicevox_open_jtalk_rc_use_user_dict: (voicevox_open_jtalk_rc open_jtalk, voicevox_user_dict user_dict) -> voicevox_result_code

  def voicevox_open_jtalk_rc_delete: (voicevox_open_jtalk_rc open_jtalk) -> void

  def voicevox_voice_model_new_from_path: (String path, voicevox_voice_model voice_model) -> voicevox_result_code
end
