module Voicevox::Core
  module Result
    SUCCEED = 0
    NOT_LOADED_OPENJTALK_DICT = 1
    FAILED_LOAD_MODEL = 2
    FAILED_GET_SUPPORTED_DEVICES = 3
    CANT_GPU_SUPPORT = 4
    FAILED_LOAD_METAS = 5
    UNINITIALIZED_STATUS = 6
    INVALID_SPEAKER_ID = 7
    INVALID_MODEL_INDEX = 8
    INFERENCE_FAILED = 9
    FAILED_EXTRACT_FULL_CONTEXT_LABEL = 10
    INVALID_UTF8_INPUT = 11
    FAILED_PARSE_KANA = 12
  end
end
