module FFI
  module Library
    def ffi_lib: (String) -> void
               | (Array[String]) -> void

    def enum: (Symbol, Array[Symbol | Integer]) -> void
            | (Class, Symbol, Array[Symbol | Integer]) -> void
  end

  class NativeType
    class INT32
    end
  end

  class Pointer
  end

  class Struct
    def self.layout: (Hash[Symbol, Symbol]) -> void
  end
end
