name: Run Rspec
on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        ruby_version:
          - "3.0"
          - "3.2"
        platform:
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download voicevox core
        id: download-voicevox-core
        uses: sevenc-nanashi/setup-voicevox@v0.1
        with:
          download-item: core
          path: voicevox_core
          version: 0.15.0-preview.8

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rake spec
        env:
          VOICEVOX_DLL_PATH: ${{ steps.download-voicevox-core.outputs.entrypoint }}
          VOICEVOX_OPEN_JTALK_DIC_DIR: ${{ steps.download-voicevox-core.outputs.open_jtalk_dic_dir }}
